package bit.soulrender.View.Menu;

import bit.soulrender.Controller.CharacterController;
import bit.soulrender.Controller.MenuController;

public class CharacterCreationScreen extends javax.swing.JPanel {

	private MenuController mc;
	private CharacterController cc;

	public CharacterCreationScreen() {
		initComponents();
		mc = new MenuController();
		cc = new CharacterController();

		mc.setCreateButtonAnimation(CreateButton, false);
		mc.setBackgroundMenu(Background);
		mc.setFont(jtCharacterName, 16);
		mc.setFont(text1, 20);
		mc.setFont(text2, 20);

		mc.getFocus(jtCharacterName);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      text2 = new javax.swing.JLabel();
      text1 = new javax.swing.JLabel();
      jtCharacterName = new javax.swing.JTextField();
      CreateButton = new javax.swing.JLabel();
      Background = new javax.swing.JLabel();

      setMaximumSize(new java.awt.Dimension(1280, 720));
      setMinimumSize(new java.awt.Dimension(1280, 720));
      setLayout(null);

      text2.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
      text2.setForeground(new java.awt.Color(255, 255, 255));
      text2.setText("Qual o nome do seu personagem?");
      add(text2);
      text2.setBounds(320, 250, 690, 70);

      text1.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
      text1.setForeground(new java.awt.Color(255, 255, 255));
      text1.setText("* Somente a classe \"Guerreiro\" está disponivel *");
      add(text1);
      text1.setBounds(180, 200, 970, 70);

      jtCharacterName.setBackground(new java.awt.Color(15, 0, 31));
      jtCharacterName.setForeground(new java.awt.Color(255, 255, 255));
      jtCharacterName.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            jtCharacterNameKeyTyped(evt);
         }
      });
      add(jtCharacterName);
      jtCharacterName.setBounds(470, 410, 330, 50);

      CreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            CreateButtonMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            CreateButtonMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            CreateButtonMouseExited(evt);
         }
      });
      add(CreateButton);
      CreateButton.setBounds(430, 510, 310, 100);

      Background.setMaximumSize(new java.awt.Dimension(1280, 720));
      Background.setMinimumSize(new java.awt.Dimension(1280, 720));
      Background.setPreferredSize(new java.awt.Dimension(1280, 720));
      Background.setRequestFocusEnabled(false);
      add(Background);
      Background.setBounds(0, 0, 1280, 720);
   }// </editor-fold>//GEN-END:initComponents

   private void jtCharacterNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCharacterNameKeyTyped
		mc.enterCheck(evt, jtCharacterName.getText(), this);
   }//GEN-LAST:event_jtCharacterNameKeyTyped

   private void CreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateButtonMouseClicked
		cc.createCharacter(jtCharacterName.getText());
		mc.toMainMenu(this);
   }//GEN-LAST:event_CreateButtonMouseClicked

   private void CreateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateButtonMouseEntered
		mc.setCreateButtonAnimation(CreateButton, true);
   }//GEN-LAST:event_CreateButtonMouseEntered

   private void CreateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateButtonMouseExited
		mc.setCreateButtonAnimation(CreateButton, false);
   }//GEN-LAST:event_CreateButtonMouseExited


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel Background;
   private javax.swing.JLabel CreateButton;
   private javax.swing.JTextField jtCharacterName;
   private javax.swing.JLabel text1;
   private javax.swing.JLabel text2;
   // End of variables declaration//GEN-END:variables

}
