package bit.soulrender.View.Menu;

import bit.soulrender.Controller.AnimationController;
import bit.soulrender.Controller.CombatController;
import bit.soulrender.Controller.MenuController;

public class GameScreen extends javax.swing.JPanel {

	/**
	 * Creates new form GameScreen
	 */
	private CombatController comC;
	private MenuController menC;
	private AnimationController ac;

	public GameScreen() {
		initComponents();
		comC = new CombatController();
		menC = new MenuController();
		ac = new AnimationController();
		menC.setRndBackground(Background);
		
		menC.setFont(TurnInfo, 30);
		menC.setFont(PlayerHpNumber, 26);
		menC.setFont(PlayerLvl, 26);
		menC.setFont(EnemyHpNumber, 26);
		menC.setFont(EnemyLvl, 26);
		menC.setFont(Result, 36);
		
		ac.BarUpdate(PlayerMp, 0);
		comC.manaCheck(ButtonSpe);
		comC.setEnemyImage(Enemy);
		comC.setEntitysLvl(PlayerLvl, EnemyLvl);
		comC.setHpTxts(PlayerHpNumber, EnemyHpNumber);
		comC.turnManagement(this, TurnInfo, ButtonAtk, ButtonSpe, ButtonDef,
				  HitEffectOnPlayer, DamageOnPlayer, Player, PlayerHpNumber, Result, PlayerHp);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      PlayerLvl = new javax.swing.JLabel();
      EnemyLvl = new javax.swing.JLabel();
      Result = new javax.swing.JLabel();
      EnemyHpNumber = new javax.swing.JLabel();
      PlayerHpNumber = new javax.swing.JLabel();
      TurnInfo = new javax.swing.JLabel();
      DamageOnPlayer = new javax.swing.JLabel();
      DamageOnEnemy = new javax.swing.JLabel();
      EnemyHp = new javax.swing.JLabel();
      PlayerMp = new javax.swing.JLabel();
      PlayerHp = new javax.swing.JLabel();
      HitEffectOnPlayer = new javax.swing.JLabel();
      HitEffectOnEnemy = new javax.swing.JLabel();
      Player = new javax.swing.JLabel();
      ButtonSurrender = new javax.swing.JLabel();
      ButtonSurrenderBackground = new javax.swing.JLabel();
      ButtonDef = new javax.swing.JLabel();
      ButtonSpe = new javax.swing.JLabel();
      ButtonAtk = new javax.swing.JLabel();
      ButtonBackground = new javax.swing.JLabel();
      Enemy = new javax.swing.JLabel();
      Background = new javax.swing.JLabel();

      setMaximumSize(new java.awt.Dimension(1280, 720));
      setMinimumSize(new java.awt.Dimension(1280, 720));
      setPreferredSize(new java.awt.Dimension(1280, 720));
      setLayout(null);

      PlayerLvl.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
      PlayerLvl.setForeground(new java.awt.Color(255, 255, 255));
      PlayerLvl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      add(PlayerLvl);
      PlayerLvl.setBounds(280, 270, 200, 40);

      EnemyLvl.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
      EnemyLvl.setForeground(new java.awt.Color(255, 255, 255));
      EnemyLvl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      add(EnemyLvl);
      EnemyLvl.setBounds(810, 140, 200, 40);

      Result.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
      Result.setForeground(new java.awt.Color(255, 255, 255));
      Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      add(Result);
      Result.setBounds(480, 90, 340, 110);

      EnemyHpNumber.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
      EnemyHpNumber.setForeground(new java.awt.Color(255, 255, 255));
      EnemyHpNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      add(EnemyHpNumber);
      EnemyHpNumber.setBounds(810, 180, 200, 50);

      PlayerHpNumber.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
      PlayerHpNumber.setForeground(new java.awt.Color(255, 255, 255));
      PlayerHpNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      add(PlayerHpNumber);
      PlayerHpNumber.setBounds(280, 310, 200, 50);

      TurnInfo.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
      TurnInfo.setForeground(new java.awt.Color(255, 255, 255));
      TurnInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      add(TurnInfo);
      TurnInfo.setBounds(370, 10, 560, 110);

      DamageOnPlayer.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
      DamageOnPlayer.setForeground(new java.awt.Color(255, 255, 255));
      DamageOnPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      add(DamageOnPlayer);
      DamageOnPlayer.setBounds(270, 520, 140, 40);

      DamageOnEnemy.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
      DamageOnEnemy.setForeground(new java.awt.Color(255, 255, 255));
      DamageOnEnemy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      add(DamageOnEnemy);
      DamageOnEnemy.setBounds(810, 390, 120, 40);

      EnemyHp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Utils/bar.png"))); // NOI18N
      add(EnemyHp);
      EnemyHp.setBounds(810, 240, 200, 25);

      PlayerMp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Utils/Energy Bar.png"))); // NOI18N
      PlayerMp.setMaximumSize(new java.awt.Dimension(0, 25));
      PlayerMp.setMinimumSize(new java.awt.Dimension(0, 25));
      add(PlayerMp);
      PlayerMp.setBounds(280, 395, 200, 15);

      PlayerHp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Utils/bar.png"))); // NOI18N
      PlayerHp.setMaximumSize(new java.awt.Dimension(0, 25));
      PlayerHp.setMinimumSize(new java.awt.Dimension(0, 25));
      add(PlayerHp);
      PlayerHp.setBounds(280, 370, 200, 25);
      add(HitEffectOnPlayer);
      HitEffectOnPlayer.setBounds(320, 510, 190, 190);
      add(HitEffectOnEnemy);
      HitEffectOnEnemy.setBounds(780, 370, 190, 190);

      Player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Characters/player.png"))); // NOI18N
      add(Player);
      Player.setBounds(220, 340, 350, 390);

      ButtonSurrender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/Button Surrender Static.png"))); // NOI18N
      ButtonSurrender.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            ButtonSurrenderMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            ButtonSurrenderMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            ButtonSurrenderMouseExited(evt);
         }
      });
      add(ButtonSurrender);
      ButtonSurrender.setBounds(30, 18, 100, 90);

      ButtonSurrenderBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menus/Interface Surrender.png"))); // NOI18N
      add(ButtonSurrenderBackground);
      ButtonSurrenderBackground.setBounds(5, 5, 150, 120);

      ButtonDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/Button Def Static.png"))); // NOI18N
      ButtonDef.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            ButtonDefMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            ButtonDefMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            ButtonDefMouseExited(evt);
         }
      });
      add(ButtonDef);
      ButtonDef.setBounds(1145, 590, 100, 90);

      ButtonSpe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/Button Spe Static.png"))); // NOI18N
      ButtonSpe.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            ButtonSpeMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            ButtonSpeMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            ButtonSpeMouseExited(evt);
         }
      });
      add(ButtonSpe);
      ButtonSpe.setBounds(1025, 590, 100, 90);

      ButtonAtk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/Button Atk Static.png"))); // NOI18N
      ButtonAtk.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            ButtonAtkMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            ButtonAtkMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            ButtonAtkMouseExited(evt);
         }
      });
      add(ButtonAtk);
      ButtonAtk.setBounds(905, 590, 100, 90);

      ButtonBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menus/Combat_interface_Buttons.png"))); // NOI18N
      add(ButtonBackground);
      ButtonBackground.setBounds(825, 555, 450, 160);
      add(Enemy);
      Enemy.setBounds(710, 290, 360, 330);

      Background.setMaximumSize(new java.awt.Dimension(1280, 720));
      Background.setMinimumSize(new java.awt.Dimension(1280, 720));
      Background.setPreferredSize(new java.awt.Dimension(1280, 720));
      Background.setRequestFocusEnabled(false);
      add(Background);
      Background.setBounds(0, 0, 1280, 720);
   }// </editor-fold>//GEN-END:initComponents

   private void ButtonAtkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAtkMouseEntered
		menC.setAtkButtonAnimation(ButtonAtk, true);
   }//GEN-LAST:event_ButtonAtkMouseEntered

   private void ButtonAtkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAtkMouseExited
		menC.setAtkButtonAnimation(ButtonAtk, false);
   }//GEN-LAST:event_ButtonAtkMouseExited

   private void ButtonAtkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAtkMouseClicked
		comC.playerActionAtk(Player, HitEffectOnEnemy, DamageOnEnemy, EnemyHpNumber,
				  EnemyHp, ButtonAtk, ButtonDef, ButtonSpe, PlayerMp);
   }//GEN-LAST:event_ButtonAtkMouseClicked

   private void ButtonSpeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSpeMouseClicked
		comC.playerActionStrAtk(Player, HitEffectOnEnemy, DamageOnEnemy, EnemyHpNumber,
				  EnemyHp, ButtonAtk, ButtonDef, ButtonSpe, PlayerMp);
   }//GEN-LAST:event_ButtonSpeMouseClicked

   private void ButtonSpeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSpeMouseEntered
		menC.setSpeButtonAnimation(ButtonSpe, true);
   }//GEN-LAST:event_ButtonSpeMouseEntered

   private void ButtonSpeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSpeMouseExited
		menC.setSpeButtonAnimation(ButtonSpe, false);
   }//GEN-LAST:event_ButtonSpeMouseExited

   private void ButtonDefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDefMouseClicked
		comC.playerActionDefense(ButtonAtk, ButtonDef, ButtonSpe, PlayerMp);
   }//GEN-LAST:event_ButtonDefMouseClicked

   private void ButtonDefMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDefMouseEntered
		menC.setDefButtonAnimation(ButtonDef, true);
   }//GEN-LAST:event_ButtonDefMouseEntered

   private void ButtonDefMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDefMouseExited
		menC.setDefButtonAnimation(ButtonDef, false);
   }//GEN-LAST:event_ButtonDefMouseExited

   private void ButtonSurrenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSurrenderMouseClicked
		menC.toMainMenu(this);
   }//GEN-LAST:event_ButtonSurrenderMouseClicked

   private void ButtonSurrenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSurrenderMouseEntered
		menC.setSurrenderButtonAnimation(ButtonSurrender, true);
   }//GEN-LAST:event_ButtonSurrenderMouseEntered

   private void ButtonSurrenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSurrenderMouseExited
		menC.setSurrenderButtonAnimation(ButtonSurrender, false);
   }//GEN-LAST:event_ButtonSurrenderMouseExited


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel Background;
   private javax.swing.JLabel ButtonAtk;
   private javax.swing.JLabel ButtonBackground;
   private javax.swing.JLabel ButtonDef;
   private javax.swing.JLabel ButtonSpe;
   private javax.swing.JLabel ButtonSurrender;
   private javax.swing.JLabel ButtonSurrenderBackground;
   private javax.swing.JLabel DamageOnEnemy;
   private javax.swing.JLabel DamageOnPlayer;
   private javax.swing.JLabel Enemy;
   private javax.swing.JLabel EnemyHp;
   private javax.swing.JLabel EnemyHpNumber;
   private javax.swing.JLabel EnemyLvl;
   private javax.swing.JLabel HitEffectOnEnemy;
   private javax.swing.JLabel HitEffectOnPlayer;
   private javax.swing.JLabel Player;
   private javax.swing.JLabel PlayerHp;
   private javax.swing.JLabel PlayerHpNumber;
   private javax.swing.JLabel PlayerLvl;
   private javax.swing.JLabel PlayerMp;
   private javax.swing.JLabel Result;
   private javax.swing.JLabel TurnInfo;
   // End of variables declaration//GEN-END:variables

}
