package bit.soulrender.View.Menu;

import bit.soulrender.Controller.MenuController;

public class HistoryScreen extends javax.swing.JPanel {

	private MenuController menC;

	public HistoryScreen() {
		initComponents();
		menC = new MenuController();
		menC.setWinAndLoses(jlWins, jlLoses);
		menC.setBackgroundMenu(Background);
		menC.historySetModel(jlHistory);
		menC.setBackButtonAnimation(BackButton, false);
		menC.setResetButtonAnimation(ResetButton, false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jlHistory = new javax.swing.JList<>();
      jlLoses = new javax.swing.JLabel();
      jlWins = new javax.swing.JLabel();
      ResetButton = new javax.swing.JLabel();
      BackButton = new javax.swing.JLabel();
      Background = new javax.swing.JLabel();

      setMaximumSize(new java.awt.Dimension(1280, 720));
      setMinimumSize(new java.awt.Dimension(1280, 720));
      setPreferredSize(new java.awt.Dimension(1280, 720));
      setLayout(null);

      jlHistory.setBackground(new java.awt.Color(15, 0, 31));
      jlHistory.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      jlHistory.setForeground(new java.awt.Color(255, 255, 255));
      jlHistory.setModel(new javax.swing.AbstractListModel<String>() {
         String[] strings = { "Cavaleiro Vermelho............Vitória" };
         public int getSize() { return strings.length; }
         public String getElementAt(int i) { return strings[i]; }
      });
      jlHistory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
      jlHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      jlHistory.setVisibleRowCount(3);
      jScrollPane1.setViewportView(jlHistory);

      add(jScrollPane1);
      jScrollPane1.setBounds(360, 200, 560, 310);

      jlLoses.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
      jlLoses.setForeground(new java.awt.Color(255, 255, 255));
      jlLoses.setText("jLabel1");
      add(jlLoses);
      jlLoses.setBounds(740, 520, 210, 40);

      jlWins.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
      jlWins.setForeground(new java.awt.Color(255, 255, 255));
      jlWins.setText("jLabel1");
      add(jlWins);
      jlWins.setBounds(390, 520, 230, 40);

      ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            ResetButtonMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            ResetButtonMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            ResetButtonMouseExited(evt);
         }
      });
      add(ResetButton);
      ResetButton.setBounds(620, 590, 310, 100);

      BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            BackButtonMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            BackButtonMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            BackButtonMouseExited(evt);
         }
      });
      add(BackButton);
      BackButton.setBounds(260, 590, 310, 100);

      Background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
      Background.setMaximumSize(new java.awt.Dimension(1280, 720));
      Background.setMinimumSize(new java.awt.Dimension(1280, 720));
      Background.setPreferredSize(new java.awt.Dimension(1280, 720));
      Background.setRequestFocusEnabled(false);
      add(Background);
      Background.setBounds(0, 0, 1280, 720);
   }// </editor-fold>//GEN-END:initComponents

   private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
		menC.toMainMenu(this);
   }//GEN-LAST:event_BackButtonMouseClicked

   private void BackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseEntered
		menC.setBackButtonAnimation(BackButton, true);
   }//GEN-LAST:event_BackButtonMouseEntered

   private void BackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseExited
		menC.setBackButtonAnimation(BackButton, false);
   }//GEN-LAST:event_BackButtonMouseExited

   private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
		menC.resetHistory();
   }//GEN-LAST:event_ResetButtonMouseClicked

   private void ResetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseEntered
		menC.setResetButtonAnimation(ResetButton, true);
   }//GEN-LAST:event_ResetButtonMouseEntered

   private void ResetButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseExited
		menC.setResetButtonAnimation(ResetButton, false);
   }//GEN-LAST:event_ResetButtonMouseExited


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel BackButton;
   private javax.swing.JLabel Background;
   private javax.swing.JLabel ResetButton;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JList<String> jlHistory;
   private javax.swing.JLabel jlLoses;
   private javax.swing.JLabel jlWins;
   // End of variables declaration//GEN-END:variables

}
