package bit.soulrender.View.Menu;

import bit.soulrender.Controller.MenuController;

public class IntroScreen extends javax.swing.JPanel {

	private MenuController mc;
	public IntroScreen() {
		initComponents();
		mc = new MenuController();
		mc.setBackgroundIntro(Background);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      Background = new javax.swing.JLabel();

      setMaximumSize(new java.awt.Dimension(1280, 720));
      setMinimumSize(new java.awt.Dimension(1280, 720));
      setLayout(null);

      Background.setMaximumSize(new java.awt.Dimension(1280, 720));
      Background.setMinimumSize(new java.awt.Dimension(1280, 720));
      Background.setPreferredSize(new java.awt.Dimension(1280, 720));
      Background.setRequestFocusEnabled(false);
      Background.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            BackgroundMouseClicked(evt);
         }
      });
      add(Background);
      Background.setBounds(0, 0, 1280, 720);
   }// </editor-fold>//GEN-END:initComponents

   private void BackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseClicked
      mc.toCharacterCreation(this);
   }//GEN-LAST:event_BackgroundMouseClicked


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel Background;
   // End of variables declaration//GEN-END:variables

}
