package bit.soulrender.View.Menu;

import bit.soulrender.Controller.MenuController;

public class PlayerStatusScreen extends javax.swing.JPanel {

	/**
	 * Creates new form PlayerStatusScreen
	 */
	private final MenuController menC = new MenuController();

	public PlayerStatusScreen() {
		initComponents();

		menC.setBackgroundMenu(Background);
		menC.setBackButtonAnimation(ButtonBack, false);

		menC.setStatusFont(personagem, nivel, vida, armadura, forca);
		menC.setStatus(jlName, jlLevel, jlHp, jlArmour, jlStrenght);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jlName = new javax.swing.JLabel();
      jlHp = new javax.swing.JLabel();
      jlArmour = new javax.swing.JLabel();
      jlStrenght = new javax.swing.JLabel();
      personagem = new javax.swing.JLabel();
      vida = new javax.swing.JLabel();
      armadura = new javax.swing.JLabel();
      forca = new javax.swing.JLabel();
      nivel = new javax.swing.JLabel();
      jlLevel = new javax.swing.JLabel();
      ButtonBack = new javax.swing.JLabel();
      Background = new javax.swing.JLabel();

      setMaximumSize(new java.awt.Dimension(1280, 720));
      setMinimumSize(new java.awt.Dimension(1280, 720));
      setPreferredSize(new java.awt.Dimension(1280, 720));
      setLayout(null);

      jlName.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      jlName.setForeground(new java.awt.Color(255, 255, 255));
      jlName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jlName.setText("<Name>");
      add(jlName);
      jlName.setBounds(710, 260, 88, 21);

      jlHp.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      jlHp.setForeground(new java.awt.Color(255, 255, 255));
      jlHp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jlHp.setText("<HP>");
      add(jlHp);
      jlHp.setBounds(710, 340, 88, 21);

      jlArmour.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      jlArmour.setForeground(new java.awt.Color(255, 255, 255));
      jlArmour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jlArmour.setText("<Armour>");
      add(jlArmour);
      jlArmour.setBounds(710, 380, 88, 21);

      jlStrenght.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      jlStrenght.setForeground(new java.awt.Color(255, 255, 255));
      jlStrenght.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jlStrenght.setText("<Strenght>");
      add(jlStrenght);
      jlStrenght.setBounds(710, 420, 88, 21);

      personagem.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      personagem.setForeground(new java.awt.Color(255, 255, 255));
      personagem.setText("Personagem");
      add(personagem);
      personagem.setBounds(490, 260, 200, 21);

      vida.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      vida.setForeground(new java.awt.Color(255, 255, 255));
      vida.setText("Vida");
      add(vida);
      vida.setBounds(490, 340, 190, 21);

      armadura.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      armadura.setForeground(new java.awt.Color(255, 255, 255));
      armadura.setText("Armadura");
      add(armadura);
      armadura.setBounds(490, 380, 190, 21);

      forca.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      forca.setForeground(new java.awt.Color(255, 255, 255));
      forca.setText("Força");
      add(forca);
      forca.setBounds(490, 420, 190, 21);

      nivel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      nivel.setForeground(new java.awt.Color(255, 255, 255));
      nivel.setText("Nível");
      add(nivel);
      nivel.setBounds(490, 300, 200, 21);

      jlLevel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
      jlLevel.setForeground(new java.awt.Color(255, 255, 255));
      jlLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jlLevel.setText("<Level>");
      add(jlLevel);
      jlLevel.setBounds(710, 300, 88, 21);

      ButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            ButtonBackMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            ButtonBackMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            ButtonBackMouseExited(evt);
         }
      });
      add(ButtonBack);
      ButtonBack.setBounds(440, 520, 310, 100);
      add(Background);
      Background.setBounds(0, 0, 1280, 720);
   }// </editor-fold>//GEN-END:initComponents

   private void ButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseClicked
		menC.toSingleplayerMenu(this);
   }//GEN-LAST:event_ButtonBackMouseClicked

   private void ButtonBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseEntered
		menC.setBackButtonAnimation(ButtonBack, true);
   }//GEN-LAST:event_ButtonBackMouseEntered

   private void ButtonBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseExited
		menC.setBackButtonAnimation(ButtonBack, false);
   }//GEN-LAST:event_ButtonBackMouseExited


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel Background;
   private javax.swing.JLabel ButtonBack;
   private javax.swing.JLabel ResetButton;
   private javax.swing.JLabel ResetButton1;
   private javax.swing.JLabel armadura;
   private javax.swing.JLabel forca;
   private javax.swing.JLabel jlArmour;
   private javax.swing.JLabel jlHp;
   private javax.swing.JLabel jlLevel;
   private javax.swing.JLabel jlName;
   private javax.swing.JLabel jlStrenght;
   private javax.swing.JLabel nivel;
   private javax.swing.JLabel personagem;
   private javax.swing.JLabel vida;
   // End of variables declaration//GEN-END:variables

}
