package bit.soulrender.View.Menu;

import bit.soulrender.Controller.MenuController;

public class ResultScreen extends javax.swing.JPanel {

	private MenuController menC = new MenuController();

	public ResultScreen(int result) {
		initComponents();
		menC.resultChange(jLabel1, result);
		menC.setBackgroundMenu(Background);
		menC.setBackButtonAnimation(BackButton, false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      BackButton = new javax.swing.JLabel();
      Background = new javax.swing.JLabel();

      setMaximumSize(new java.awt.Dimension(1280, 720));
      setMinimumSize(new java.awt.Dimension(1280, 720));
      setPreferredSize(new java.awt.Dimension(1280, 720));
      setLayout(null);

      jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Descrição muito pika e subiu de nivel");
      add(jLabel1);
      jLabel1.setBounds(402, 160, 500, 175);

      BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            BackButtonMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            BackButtonMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            BackButtonMouseExited(evt);
         }
      });
      add(BackButton);
      BackButton.setBounds(440, 380, 310, 100);
      add(Background);
      Background.setBounds(0, 0, 1280, 720);
   }// </editor-fold>//GEN-END:initComponents

   private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
		menC.toMainMenu(this);
   }//GEN-LAST:event_BackButtonMouseClicked

   private void BackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseEntered
		menC.setBackButtonAnimation(BackButton, true);
   }//GEN-LAST:event_BackButtonMouseEntered

   private void BackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseExited
		menC.setBackButtonAnimation(BackButton, false);
   }//GEN-LAST:event_BackButtonMouseExited


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel BackButton;
   private javax.swing.JLabel Background;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration//GEN-END:variables

}
