package bit.soulrender.View.Menu;

import bit.soulrender.Controller.MenuController;

public class SingleplayerScreen extends javax.swing.JPanel {

	/**
	 * Creates new form SingleplayerScreen
	 */
	MenuController mc;

	public SingleplayerScreen() {
		initComponents();
		mc = new MenuController();
		mc.setBackgroundMenu(Background);
		mc.setPlayButtonAnimation(PlayButton, false);
		mc.setStatusButtonAnimation(StatusButton, false);
		mc.setBackButtonAnimation(BackButton, false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      BackButton = new javax.swing.JLabel();
      StatusButton = new javax.swing.JLabel();
      PlayButton = new javax.swing.JLabel();
      Background = new javax.swing.JLabel();

      setMaximumSize(new java.awt.Dimension(1280, 720));
      setMinimumSize(new java.awt.Dimension(1280, 720));
      setLayout(null);

      BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            BackButtonMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            BackButtonMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            BackButtonMouseExited(evt);
         }
      });
      add(BackButton);
      BackButton.setBounds(440, 520, 310, 100);

      StatusButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            StatusButtonMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            StatusButtonMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            StatusButtonMouseExited(evt);
         }
      });
      add(StatusButton);
      StatusButton.setBounds(440, 380, 310, 100);

      PlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            PlayButtonMouseClicked(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            PlayButtonMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            PlayButtonMouseExited(evt);
         }
      });
      add(PlayButton);
      PlayButton.setBounds(440, 240, 310, 100);

      Background.setMaximumSize(new java.awt.Dimension(1280, 720));
      Background.setMinimumSize(new java.awt.Dimension(1280, 720));
      Background.setPreferredSize(new java.awt.Dimension(1280, 720));
      Background.setRequestFocusEnabled(false);
      add(Background);
      Background.setBounds(0, 0, 1280, 720);
   }// </editor-fold>//GEN-END:initComponents

   private void PlayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayButtonMouseClicked
		mc.toGame(this);
   }//GEN-LAST:event_PlayButtonMouseClicked

   private void PlayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayButtonMouseEntered
		mc.setPlayButtonAnimation(PlayButton, true);
   }//GEN-LAST:event_PlayButtonMouseEntered

   private void PlayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayButtonMouseExited
		mc.setPlayButtonAnimation(PlayButton, false);
   }//GEN-LAST:event_PlayButtonMouseExited

   private void StatusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusButtonMouseClicked
		mc.toStatusScreen(this);
   }//GEN-LAST:event_StatusButtonMouseClicked

   private void StatusButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusButtonMouseEntered
		mc.setStatusButtonAnimation(StatusButton, true);
   }//GEN-LAST:event_StatusButtonMouseEntered

   private void StatusButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusButtonMouseExited
		mc.setStatusButtonAnimation(StatusButton, false);
   }//GEN-LAST:event_StatusButtonMouseExited

   private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
		mc.toMainMenu(this);
   }//GEN-LAST:event_BackButtonMouseClicked

   private void BackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseEntered
		mc.setBackButtonAnimation(BackButton, true);
   }//GEN-LAST:event_BackButtonMouseEntered

   private void BackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseExited
		mc.setBackButtonAnimation(BackButton, false);
   }//GEN-LAST:event_BackButtonMouseExited


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel BackButton;
   private javax.swing.JLabel Background;
   private javax.swing.JLabel PlayButton;
   private javax.swing.JLabel StatusButton;
   // End of variables declaration//GEN-END:variables

}
